added index.html & CSS
WeirdAlex03/Project-EverGreen pull request #6
Opened 2024-10-03 23:24 UTC by rancescolon

HTML and CSS

2024-10-03 23:35 UTC, Eric-Butcher commented on evergreen/index.html
Change Ever Green to Evergreen.

Also I would eliminate the sections about the clubs other projects. For now lets just focus on the evergreen greenhouse. Also for the contact us, I would add the discord invite link: https://discord.com/invite/QMHjt65z7a.

2024-10-03 23:35 UTC, Eric-Butcher commented on evergreen/styles.css
I don't know CSS enough to authoritatively approve this on my own. But it looks ok so far to my eyes.

2024-10-03 23:38 UTC, WeirdAlex03 reviewed
I'm not great on my CSS but lgtm. With the "Project Evergreen" changes I'll signoff

2024-10-03 23:56 UTC, WeirdAlex03 requested changes

2024-10-03 23:56 UTC, WeirdAlex03 commented on evergreen/index.html
> +    <title>Project-Evergreen</title>
Just "`Project Evergreen`" - space, not dash

2024-10-04 00:01 UTC, WeirdAlex03 approved these changes
:shipit:

2024-10-04 00:06 UTC, Eric-Butcher approved these changes

2024-10-04 00:06 UTC, merged