Hotfix/redirect
WeirdAlex03/Project-EverGreen pull request #65
Opened 2024-12-08 19:28 UTC by giagermain

fixed readme description for redirects

2024-12-08 19:29 UTC, sumanyuj submitted a review, later dismissed
LGTM

2024-12-08 20:16 UTC, WeirdAlex03 commented on README.md
> +Please note that requests to port 8080 are redirected to port 80 or 443 as static files are hosted through nginx. Port 443 is used in instances where certs are present. Port 80 is used in instances w
Last part is a little clunky to me
```suggestion
Please note that requests to port 8080 are redirected to port 80 or 443 as static files are hosted through nginx. Port 443 is used in instances where certs are present. Port 80 is used in instances where they are not present. Requests to port 80 will be upgraded to HTTPS (443) if that is in use.
```

2024-12-08 20:18 UTC, WeirdAlex03 requested changes
This will be the last PR allowed before I turn on requiring format checking to pass again

(Also for future reference, `docs/` is a more fitting branch name for this kinda thing, but I'm not gonna stop you over that)

2024-12-09 02:28 UTC, WeirdAlex03 approved these changes
:shipit:

2024-12-09 04:21 UTC, merged